# Generated by Django 5.0.6 on 2026-09-22 20:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('equipment', models.CharField(blank=True, help_text='Machine or unit being worked on.', max_length=160)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('INVOICED', 'Invoiced'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('labour_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('labour_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('other_costs', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Transport, hired tools, subcontracted work.', max_digits=16)),
                ('quoted_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='What the customer is being charged for the job.', max_digits=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='sales.customer')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JobMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=16)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_issued', models.BooleanField(default=False, editable=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='jobs.jobcard')),
            ],
        ),
    ]
