# Generated by Django 5.0.6 on 2026-09-22 21:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='equipment',
            field=models.CharField(blank=True, help_text='Which machine you are working on.', max_length=160),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='other_costs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Transport, hired tools, work given to someone else.', max_digits=16),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='quoted_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='What you are charging the customer for this job.', max_digits=16),
        ),
    ]
