# Generated by Django 5.0.6 on 2026-09-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobcard_equipment_alter_jobcard_other_costs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='due_date',
            field=models.DateField(blank=True, help_text='When you promised it to the customer.', null=True),
        ),
    ]
