from decimal import Decimal

from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models, transaction

from core.models import TimeStampedModel

# Company prefix used at the front of every item code, e.g. TIL-BRG-001.
COMPANY_PREFIX = getattr(settings, "ITEM_CODE_COMPANY_PREFIX", "TIL")


class UnitOfMeasure(models.Model):
    """Pcs, Set, Metre, Kg, Litre, Box ..."""

    name = models.CharField(max_length=40, unique=True)
    abbreviation = models.CharField(max_length=10, unique=True)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Units of measure"

    def __str__(self):
        return self.abbreviation


class Category(models.Model):
    """
    A product group. Its `code` becomes the middle part of the item code,
    and `last_sequence` is the running counter inside that group.

        Bearings      -> BRG -> TIL-BRG-001, TIL-BRG-002 ...
        Cutting Discs -> CTD -> TIL-CTD-001 ...
    """

    name = models.CharField(max_length=80, unique=True)
    code = models.CharField(
        max_length=4,
        unique=True,
        help_text="Three letters used in the item code, e.g. BRG for Bearings.",
    )
    description = models.CharField(max_length=200, blank=True)
    last_sequence = models.PositiveIntegerField(default=0, editable=False)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.code = self.code.upper().strip()
        super().save(*args, **kwargs)

    @transaction.atomic
    def take_next_code(self, padding=3):
        """Reserve the next item code in this category. Locks the row."""
        category = Category.objects.select_for_update().get(pk=self.pk)
        category.last_sequence += 1
        category.save(update_fields=["last_sequence"])
        self.last_sequence = category.last_sequence
        return (
            f"{COMPANY_PREFIX}-{category.code}-"
            f"{str(category.last_sequence).zfill(padding)}"
        )


class Supplier(TimeStampedModel):
    name = models.CharField(max_length=120, unique=True)
    contact_person = models.CharField(max_length=80, blank=True)
    phone = models.CharField(max_length=40, blank=True)
    email = models.EmailField(blank=True)
    address = models.TextField(blank=True)
    country = models.CharField(max_length=60, default="Tanzania")
    is_foreign = models.BooleanField(
        default=False,
        help_text="Tick this if goods come from outside Tanzania.",
    )
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class ItemType(models.TextChoices):
    STOCK = "STOCK", "For sale"
    CONSUMABLE = "CONSUMABLE", "Used in the workshop"
    SERVICE = "SERVICE", "Service - nothing on the shelf"


class Item(TimeStampedModel):
    """
    One row per product or service.

    `code`        - generated by the system: TIL-BRG-001
    `part_number` - the manufacturer's own number: 6204, 3240.
                    Kept separate because that is what customers quote,
                    and it must stay searchable.
    """

    code = models.CharField(max_length=24, unique=True, editable=False)
    part_number = models.CharField(
        max_length=60,
        blank=True,
        db_index=True,
        help_text="The number on the part itself, e.g. 6204.",
    )
    barcode = models.CharField(max_length=64, blank=True, db_index=True)

    name = models.CharField(max_length=160)
    description = models.TextField(blank=True)
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, related_name="items"
    )
    unit = models.ForeignKey(
        UnitOfMeasure, on_delete=models.PROTECT, related_name="items"
    )
    item_type = models.CharField(
        max_length=20, choices=ItemType.choices, default=ItemType.STOCK
    )

    # --- stock position -------------------------------------------------
    quantity_on_hand = models.DecimalField(
        max_digits=14, decimal_places=3, default=Decimal("0"), editable=False
    )
    minimum_level = models.DecimalField(
        max_digits=14,
        decimal_places=3,
        default=Decimal("0"),
        validators=[MinValueValidator(Decimal("0"))],
        help_text="Send an email when stock drops to this number.",
    )
    reorder_quantity = models.DecimalField(
        max_digits=14, decimal_places=3, default=Decimal("0")
    )

    # --- money ----------------------------------------------------------
    average_cost = models.DecimalField(
        max_digits=16,
        decimal_places=2,
        default=Decimal("0"),
        editable=False,
        help_text="What one piece costs us on average, in TZS.",
    )
    last_purchase_cost = models.DecimalField(
        max_digits=16, decimal_places=2, default=Decimal("0"), editable=False
    )
    selling_price = models.DecimalField(
        max_digits=16, decimal_places=2, default=Decimal("0")
    )

    location = models.CharField(
        max_length=80, blank=True, help_text="Which shelf or rack."
    )
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ["name"]
        indexes = [models.Index(fields=["name"])]

    def __str__(self):
        return f"{self.code} - {self.name}"

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = self.category.take_next_code()
        super().save(*args, **kwargs)

    # --- helpers --------------------------------------------------------
    @property
    def tracks_stock(self):
        return self.item_type in (ItemType.STOCK, ItemType.CONSUMABLE)

    @property
    def is_below_minimum(self):
        """
        An item only counts as running out if somebody set a level for it.
        Without this the whole catalogue would look low the day it is created,
        and the sidebar badge would disagree with the low-stock report.
        """
        return (
            self.tracks_stock
            and self.minimum_level > 0
            and self.quantity_on_hand <= self.minimum_level
        )

    @property
    def stock_value(self):
        return self.quantity_on_hand * self.average_cost

    @property
    def margin_percent(self):
        if not self.average_cost:
            return None
        return (self.selling_price - self.average_cost) / self.average_cost * 100

    def recalculate_quantity(self):
        """Rebuild quantity_on_hand from the movement ledger. Use for audits."""
        from inventory.models import StockMovement

        self.quantity_on_hand = StockMovement.objects.balance_for(self)
        self.save(update_fields=["quantity_on_hand"])
        return self.quantity_on_hand
