# Generated by Django 5.0.6 on 2026-09-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='receives_stock_alerts',
            field=models.BooleanField(default=False, help_text='Send this person the daily email about items running out.'),
        ),
    ]
