# Generated by Django 5.0.6 on 2026-09-22 20:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_at_alert', models.DecimalField(decimal_places=3, max_digits=14)),
                ('minimum_at_alert', models.DecimalField(decimal_places=3, max_digits=14)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='catalog.item')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('PURCHASE_IN', 'Goods received (purchase)'), ('SALE_OUT', 'Sold / delivered'), ('JOB_ISSUE', 'Issued to a job'), ('RETURN_IN', 'Returned by customer'), ('RETURN_OUT', 'Returned to supplier'), ('ADJUSTMENT_IN', 'Stock count - increase'), ('ADJUSTMENT_OUT', 'Stock count - decrease'), ('OPENING', 'Opening balance')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Landed cost per unit at the moment of the movement, in TZS.', max_digits=16)),
                ('movement_date', models.DateField(default=django.utils.timezone.now)),
                ('source_document', models.CharField(blank=True, max_length=20)),
                ('source_reference', models.CharField(blank=True, db_index=True, max_length=40)),
                ('balance_after', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.item')),
            ],
            options={
                'ordering': ['-movement_date', '-id'],
                'indexes': [models.Index(fields=['item', 'movement_date'], name='inventory_s_item_id_c55b35_idx'), models.Index(fields=['movement_type', 'movement_date'], name='inventory_s_movemen_86911f_idx')],
            },
        ),
    ]
