# Generated by Django 5.0.6 on 2026-09-22 21:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE_IN', 'Bought - added to store'), ('SALE_OUT', 'Sold - given to customer'), ('JOB_ISSUE', 'Used on a workshop job'), ('RETURN_IN', 'Customer brought it back'), ('RETURN_OUT', 'Sent back to supplier'), ('ADJUSTMENT_IN', 'Counted - found more'), ('ADJUSTMENT_OUT', 'Counted - found less'), ('OPENING', 'Starting stock')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='What one piece cost us at that moment, in TZS.', max_digits=16),
        ),
    ]
