# Generated by Django 5.0.6 on 2026-09-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmovement_movement_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=32, unique=True)),
                ('text', models.TextField()),
                ('source', models.CharField(choices=[('grok', 'Written by Grok'), ('system', 'Written by the system')], default='system', max_length=10)),
                ('facts', models.JSONField(default=dict, help_text='Exactly the figures the text was written from.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
