# Generated by Django 5.0.6 on 2026-09-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_briefing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE_IN", "Bought - added to store"),
                    ("SALE_OUT", "Sold - given to customer"),
                    ("JOB_ISSUE", "Used on a workshop job"),
                    ("RETURN_IN", "Customer brought it back"),
                    ("RETURN_OUT", "Sent back to supplier"),
                    ("ADJUSTMENT_IN", "Counted - found more"),
                    ("ADJUSTMENT_OUT", "Counted - found less"),
                    ("OPENING", "Starting stock"),
                    ("COST_CORRECTION", "Cost price corrected"),
                ],
                max_length=20,
            ),
        ),
    ]
