# Generated by Django 5.0.6 on 2026-09-22 20:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('supplier_invoice_no', models.CharField(blank=True, max_length=60)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='How many TZS one unit of the currency buys. Use 1 for TZS.', max_digits=12)),
                ('freight_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('customs_duty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('clearing_charges', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('other_charges', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('allocation_method', models.CharField(choices=[('BY_VALUE', 'Share charges by line value'), ('BY_QUANTITY', 'Share charges by quantity'), ('BY_WEIGHT', 'Share charges by weight')], default='BY_VALUE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECEIVED', 'Received into stock'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='catalog.supplier')),
            ],
            options={
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Supplier price per unit in the purchase currency.', max_digits=16)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Only needed when charges are shared by weight.', max_digits=12)),
                ('allocated_charges', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=16)),
                ('landed_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=16)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchase')),
            ],
        ),
    ]
