# Generated by Django 5.0.6 on 2026-09-22 21:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='allocation_method',
            field=models.CharField(choices=[('BY_VALUE', 'By price - dearer items carry more'), ('BY_QUANTITY', 'By quantity - each piece the same'), ('BY_WEIGHT', 'By weight - heavier items carry more')], default='BY_VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='How many TZS for 1 of that currency. Put 1 if you paid in TZS.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Not added yet'), ('RECEIVED', 'Added to the store'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text="The supplier's price for one piece, in the currency you paid.", max_digits=16),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Only needed if you share the extra costs by weight.', max_digits=12),
        ),
    ]
