# Generated by Django 5.0.6 on 2026-09-22 20:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(help_text='Short group code used in item numbers, e.g. BRG for Bearings.', max_length=4, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('last_sequence', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Units of measure',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(default='Tanzania', max_length=60)),
                ('is_foreign', models.BooleanField(default=False, help_text='Foreign suppliers bring freight, duty and clearing costs.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=24, unique=True)),
                ('part_number', models.CharField(blank=True, db_index=True, help_text='Manufacturer or OEM number, e.g. 6204.', max_length=60)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('STOCK', 'Stock item (for sale)'), ('CONSUMABLE', 'Consumable (used internally / on jobs)'), ('SERVICE', 'Service (no stock held)')], default='STOCK', max_length=20)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=14)),
                ('minimum_level', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='An email alert is raised when stock falls to or below this.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reorder_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('average_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Weighted average landed cost per unit, in TZS.', max_digits=16)),
                ('last_purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=16)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('location', models.CharField(blank=True, help_text='Shelf / rack / store.', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.unitofmeasure')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='catalog_ite_name_9b7e7e_idx')],
            },
        ),
    ]
