# Generated by Django 5.0.6 on 2026-09-22 21:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(help_text='Three letters used in the item code, e.g. BRG for Bearings.', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='What one piece costs us on average, in TZS.', max_digits=16),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('STOCK', 'For sale'), ('CONSUMABLE', 'Used in the workshop'), ('SERVICE', 'Service - nothing on the shelf')], default='STOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, help_text='Which shelf or rack.', max_length=80),
        ),
        migrations.AlterField(
            model_name='item',
            name='minimum_level',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Send an email when stock drops to this number.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='item',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, help_text='The number on the part itself, e.g. 6204.', max_length=60),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_foreign',
            field=models.BooleanField(default=False, help_text='Tick this if goods come from outside Tanzania.'),
        ),
    ]
