# Generated by Django 5.0.6 on 2026-09-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DELIVERED', 'Customer took the goods'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverynoteline',
            name='description',
            field=models.CharField(blank=True, help_text='Use this if you want different wording on the printed paper.', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PART_PAID', 'Part paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.CharField(blank=True, help_text='Use this if you want different wording on the printed paper.', max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to customer'), ('ACCEPTED', 'Accepted'), ('INVOICED', 'Turned into an invoice'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='description',
            field=models.CharField(blank=True, help_text='Use this if you want different wording on the printed paper.', max_length=200),
        ),
    ]
